In [ ]:
import numpy as np 
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.metrics import log_loss
from sklearn.metrics import accuracy_score

In [ ]:
lenses = pd.read_csv('/content/len.csv',sep='\s+',header=None)
#lenses.colums=["age","perscription","astigmatic","tears","lenses"]
lenses.rename(columns={0:'age',1:'perscription',2:'astigmatic', 3:'tears',4:'lenses'}, inplace=True)
lenses.head()

age  perscription  astigmatic  tears  lenses
0    1             1           1      1       3
1    1             1           1      2       2
2    1             1           2      1       3
3    1             1           2      2       1
4    1             2           1      1       3

In [ ]:
df=lenses.corr()
df

age  perscription  astigmatic     tears    lenses
age           1.000000     -0.057304    0.029566 -0.019388 -0.019306
perscription -0.057304      1.000000    0.002983  0.004815  0.142664
astigmatic    0.029566      0.002983    1.000000 -0.000801 -0.177604
tears        -0.019388      0.004815   -0.000801  1.000000 -0.729569
lenses       -0.019306      0.142664   -0.177604 -0.729569  1.000000

Naive Bayes


In [ ]:
import numpy as np
import pandas as pd
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
# Building Phase
# training the model on training set
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=0)
gnb = GaussianNB()
gnb.fit(X_train, y_train)
# making predictions on the testing set
y_pred = gnb.predict(X_test)


In [ ]:
# Performancec Evaluation
print("Results Using Gaussian Naive Bayes Classifier\n\n")
print("Confusion Matrix:\n ", confusion_matrix(y_test, y_pred))
print ("Accuracy : ", accuracy_score(y_test,y_pred)*100)
print("Report :\n ", classification_report(y_test, y_pred))

Results Using Gaussian Naive Bayes Classifier


Confusion Matrix:
  [[ 8  0  0]
 [ 0 24  0]
 [ 8  4 37]]
Accuracy :  85.18518518518519
Report :
                precision    recall  f1-score   support

           1       0.50      1.00      0.67         8
           2       0.86      1.00      0.92        24
           3       1.00      0.76      0.86        49

    accuracy                           0.85        81
   macro avg       0.79      0.92      0.82        81
weighted avg       0.91      0.85      0.86        81

